version: '3'
services: 
    gate: 
        build: ./src/gate
        restart: always
        ports:
            - "5000:5000"
    user:
        build: ./src/user
        restart: always
    match: 
        build: ./src/match
        restart: always
    deck:
        build: ./src/deck
        restart: always
    match_development:
        build: ./src/match_development
        restart: always
